# Generated by Django 4.2.1 on 2023-05-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='adresse',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='phonenumber',
            field=models.IntegerField(max_length=20, null=True),
        ),
    ]
