# Generated by Django 4.2.1 on 2023-12-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=30)),
                ("prenom", models.CharField(max_length=30)),
                ("number", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=100)),
                ("sujet", models.CharField(max_length=250)),
                ("qustion", models.TextField()),
            ],
        ),
    ]
