# Generated by Django 4.2.1 on 2023-12-26 13:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_contact"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="qustion",
            new_name="question",
        ),
    ]
