# Generated by Django 4.2.1 on 2023-05-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_adresse_users_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phonenumber',
            field=models.IntegerField(null=True),
        ),
    ]
