# Generated by Django 4.2.1 on 2023-05-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_users_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phonenumber',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
