# Generated by Django 4.2.1 on 2024-01-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_rename_qustion_contact_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="sujet",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
