# Generated by Django 4.2.1 on 2023-06-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_users_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='nom',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='prenom',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
