# Generated by Django 4.2.1 on 2023-06-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_users_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='entreprise',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='nom',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='prenom',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
