# Generated by Django 4.2.1 on 2023-05-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('adresse', models.CharField(max_length=10, null=True)),
                ('order_list', models.JSONField(null=True)),
            ],
        ),
    ]
