# Generated by Django 4.2.1 on 2023-06-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='block',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='pay',
            field=models.BooleanField(default=False),
        ),
    ]
