# Generated by Django 4.2.1 on 2023-05-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='adresse',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
