# Generated by Django 4.2.1 on 2023-10-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_order_done"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="paspaye",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="validable",
            field=models.BooleanField(default=False),
        ),
    ]
