# Generated by Django 4.2.1 on 2023-06-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_order_block_alter_order_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='block',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay',
            field=models.BooleanField(default=False),
        ),
    ]
