# Generated by Django 4.2.1 on 2023-05-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_file_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_list',
        ),
        migrations.AddField(
            model_name='order',
            name='entreprise',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='order',
            name='phonenumber',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
