# Generated by Django 4.2.1 on 2023-05-31 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_file',
            field=models.FileField(null=True, upload_to='upload/'),
        ),
    ]
