# Generated by Django 4.2.1 on 2023-06-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_order_order_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='nom',
        ),
        migrations.AddField(
            model_name='order',
            name='prenom',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
