# Generated by Django 4.2.1 on 2023-06-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_name_order_nom_order_prenom'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
