# Generated by Django 4.2.1 on 2023-06-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='create_dt',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='modify_dt',
            field=models.DateField(auto_now=True),
        ),
    ]
